### ISSUE TITLE
Memory leak Linux Client node Testnet version 4.2.412.6

### ISSUE THREAD

**Issue by Toki1975** [CREDITSCOM/node#10] opened 2019-05-28 09:12 UTC
Describe the bug:

Used amount of memory used by Linux client is not stable/regular.

The amount of memory used by the client node is increasing little by little. After starting the node the memory level used is about 800mb, but after 19  hours  as you can see in the attached log file, client use more than 7.5GB of memory. Which could crash / make unstable the system if the maximum available memory level available is reached.

The attached log file was generated with the following command that checks every minute the amount of memory used by the specified process:

watch -n 60 "pmap -x 5648 | grep total >> /home/credits/Clientmemory_20190516_0844PM.txt"

Where the number 5648 is the PID of the node client process

PID of the node client process is know by the following command:

ps -ef | grep client

The log file containing 1151 lines, which represents
1151 minutes or 19 hours and 11 minutes

Desktop (please complete the following information):

OS: Ubuntu 18.04
Version: Client node Testnet version 4.2.412.6

*
[Clientmemory_20190527_0155PM.txt](https://github.com/CREDITSCOM/node/files/3226051/Clientmemory_20190527_0155PM.txt)

**Comment by kondrashovsv** [comment] 2019-05-28 12:46
Duplicate of #3

**Comment by Toki1975** [comment] 2019-05-28 13:09
Hi Kondrashovsv,

Maybe can you delete the first issue. because this one concern the last version provided.
Best regards,

Toki.

**Comment by Toki1975** [comment] 2019-05-30 17:06
Update:

It's been almost 2 days and 6 hours that i have restarted the client node on my Vps.
The first 1082 minutes the client node was using a total kB 1684480 but suddenly in 8 minutes the total use of memory by client node jumped to total kB 3988492.

After this peak and  2133 minutes later, memory use  has decreased to total kB 3321144.

Client memory log file is in attach and my log files are available if someone want  them to analyse what caused the pic of memory use at minute 1082. 

[Clientmemory_20190528_1124AM.txt](https://github.com/CREDITSCOM/node/files/3237979/Clientmemory_20190528_1124AM.txt)

**Comment by Toki1975** [comment] 2019-06-03 13:43
Update:

Node client are running since 31/05/2019 15h26PM until now 03/06/2019 at 15.36PM. 3 days and memory client used is stable at 1036 mb. I will monitor it for 24h and it it stay table i will ask to close the issue. Find memory log and print screen in attach.

[Clientmemory_20190531_1526PM.txt](https://github.com/CREDITSCOM/node/files/3247821/Clientmemory_20190531_1526PM.txt)
![2019-06-03_152953](https://user-images.githubusercontent.com/50962779/58806242-10287480-8616-11e9-9b00-5d900838500b.png)

**Comment by DmitriyYashenko** [comment] 2019-06-04 07:42
Thank you

**Closed by DmitriyYashenko** 2019-06-04 07:42 UTC
Labels: duplicate
